services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://:29092,PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  main-server:
    build:
      context: ./server
    container_name: main-server
    depends_on:
      - kafka
    environment:
      PORT: 4000
      KAFKA_BROKERS: kafka:29092
    ports:
      - "44000:4000"

  main-client:
    build:
      context: ./client
    container_name: main-client
    depends_on:
      - main-server
    ports:
      - "45173:5173"
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 5173"

  crs-server:
    build:
      context: ./systems/crs-system/server
    container_name: crs-server
    depends_on:
      - kafka
    environment:
      PORT: 4002
      KAFKA_BROKERS: kafka:29092
    ports:
      - "44002:4002"

  crs-client:
    build:
      context: ./systems/crs-system/client
    container_name: crs-client
    depends_on:
      - crs-server
    ports:
      - "45174:5174"
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 5174"

  tlrc-server:
    build:
      context: ./systems/tlrc-login-system/server
    container_name: tlrc-server
    depends_on:
      - kafka
    environment:
      PORT: 4001
      KAFKA_BROKERS: kafka:29092
    ports:
      - "44001:4001"

  tlrc-client:
    build:
      context: ./systems/tlrc-login-system/client
    container_name: tlrc-client
    depends_on:
      - tlrc-server
    ports:
      - "45175:5175"
    command: sh -c "npm run dev -- --host 0.0.0.0 --port 5175"

